### ISSUE TITLE
今日运势排序问题

### ISSUE THREAD

**Issue by Natane0808** [Travellerrr/AronaBot#7]
jrys.json  里 luckyStar 和 fortuneSummary 中哪个排序的优先级更高?

foruneSummary应该怎么排序,"大吉+官运+财运"和"大吉+财运+官运"程度是一样的吗

~~~json
[
  "大吉+财运+才艺",
  "大吉+财运+官运",
  "大吉+财运",
  "大吉+才艺",
  "大吉+官运+财运+才艺",
  "大吉+官运+财运",
  "大吉+官运+才艺",
  "大吉+官运",
  "大吉",
  "中吉+财运",
  "中吉+才艺",
  "中吉+官运",
  "中吉",
  "吉带凶",
  "吉",
  "凶带吉",
  "凶"
]
~~~

**Comment by Echomirix** [comment]
这个json文件是我从某项目上抓下来 的，没有经过任何的加工，其中的`luckyStar`和`fortuneSummary`不分优先级。抽取运势仅是生成一个1到最大id的随机数，再从该json中选取对应内容。

具体的文件可以参考[这个项目的文件](https://github.com/SLiGe/CqApiServer/blob/master/src%2Fmain%2Fresources%2Fsql%2Fqr_data.sql)
